#!/usr/bin/env bash
set -eu

# env vars used in config.php
export SERVER_ENVIRONMENT='TEST_ENVIRONMENT'
export LISTENR_URL='localhost:8000'
export MOCK_PORT='7899'

# reset database each time (remember to set DB_PASSWORD in env)
mysql --user="root" --password=$DB_PASSWORD < sql/model.sql

# start php server in the background
cd listenr
php -S $LISTENR_URL index.php &

# run cucumber tests
cd ../component-tests/cucumber
bundle exec cucumber "$@"

# clean-up (kill php server)
kill $(ps | grep 'php -S' | head -1 | awk '{print $1}')

# hang if processes aren't killed
wait
