#!/usr/bin/env bash

export SERVER_ENVIRONMENT='TEST_ENVIRONMENT'
export LISTENR_URL='localhost:8000'
export MOCK_PORT='7899'

# reset database each time (remember to set DB_PASSWORD in env)
mysql --user="root" --password=$DB_PASSWORD < sql/setup.sql

# start php server in the background
php -S $LISTENR_URL index.php &

cd component-tests/cucumber
# run cucumber tests
bundle exec cucumber "$@"

# clean-up (kill php server)
kill $(ps | grep 'php -S' | head -1 | awk '{print $1}')
cd ../../

wait
